# Generated by Django 3.2.7 on 2021-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listelement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='price',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
    ]
