# Generated by Django 3.2.7 on 2021-10-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cupon'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
